[package]
name = "ferry-python"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
name = "_native"
crate-type = ["cdylib", "rlib"]

[dependencies]
ferry-core = { path = "../ferry-core" }
ferry-sources = { path = "../ferry-sources" }
ferry-destinations = { path = "../ferry-destinations" }
pyo3.workspace = true
pyo3-arrow.workspace = true
tokio.workspace = true
once_cell.workspace = true
serde_json.workspace = true
chrono.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

[features]
extension-module = ["pyo3/extension-module"]
