[package]
name = "ferry-core"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
arrow.workspace = true
arrow-array.workspace = true
arrow-schema.workspace = true
duckdb.workspace = true
tokio.workspace = true
serde.workspace = true
serde_json.workspace = true
yaml_serde.workspace = true
toml.workspace = true
governor.workspace = true
xxhash-rust.workspace = true
anyhow.workspace = true
tracing.workspace = true
thiserror.workspace = true
async-trait.workspace = true
regex.workspace = true
chrono.workspace = true
uuid.workspace = true
r2d2.workspace = true
futures.workspace = true
rand.workspace = true
url.workspace = true
minijinja.workspace = true
http.workspace = true

[dev-dependencies]
tempfile.workspace = true
ferry-sources = { path = "../ferry-sources" }
ferry-destinations = { path = "../ferry-destinations" }
